# Generated by Django 5.0.1 on 2024-02-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrients_model',
            old_name='Fiber_total_dietary',
            new_name='Fat',
        ),
        migrations.RenameField(
            model_name='nutrients_model',
            old_name='Total_lipid_fat',
            new_name='Fiber',
        ),
    ]
