# Generated by Django 5.0.1 on 2024-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_fiber_total_dietary_nutrients_model_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Energy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Weight', models.CharField(choices=[('Gain', 'Gain'), ('Loss', 'Loss')], max_length=4)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('Region', models.CharField(max_length=10)),
                ('Generic_Disease', models.CharField(max_length=20)),
                ('Allergies', models.CharField(max_length=20)),
            ],
        ),
    ]
