# Generated by Django 5.0.3 on 2024-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_energy_model_recommendation_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation_model',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='recommendation_model',
            name='Allergies',
        ),
        migrations.RemoveField(
            model_name='recommendation_model',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='recommendation_model',
            name='Generic_Disease',
        ),
        migrations.RemoveField(
            model_name='recommendation_model',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='recommendation_model',
            name='Weight',
        ),
        migrations.AddField(
            model_name='recommendation_model',
            name='Vitamin',
            field=models.CharField(choices=[('vitamin-a', 'Vitamin A'), ('vitamin-b1', 'Vitamin B1'), ('vitamin-b2', 'Vitamin B2'), ('vitamin-b3', 'Vitamin B3'), ('vitamin-b5', 'Vitamin B5'), ('vitamin-b6', 'Vitamin B6'), ('vitamin-b7', 'Vitamin B7'), ('vitamin-b9', 'Vitamin B9'), ('vitamin-b12', 'Vitamin B12'), ('vitamin-c', 'Vitamin C'), ('vitamin-d', 'Vitamin D'), ('vitamin-e', 'Vitamin E'), ('vitamin-k', 'Vitamin K')], default='vitamin-a', max_length=20),
            preserve_default=False,
        ),
    ]
